language: ruby
cache: bundler
services:
  - postgresql
  - mysql
dist: trusty
addons:
  postgresql: "9.6"
rvm:
  - 2.6.4
  - 2.5.6
  - 2.4.7
  - jruby-9.2.8.0

env:
  global:
    - COVERALLS=true 
  matrix:
    - DB=postgres
    - DB=mysql

gemfile:
  - gemfiles/Gemfile.rails-4.0.rb
  - gemfiles/Gemfile.rails-4.1.rb
  - gemfiles/Gemfile.rails-4.2.rb
  - gemfiles/Gemfile.rails-5.0.rb
  - gemfiles/Gemfile.rails-5.1.rb
  - gemfiles/Gemfile.rails-5.2.rb
  - gemfiles/Gemfile.rails-6.0.rb

before_install:
  - gem update bundler

matrix:
  exclude:
    - rvm: 2.4.7
      gemfile: gemfiles/Gemfile.rails-4.0.rb
    - rvm: 2.4.7
      gemfile: gemfiles/Gemfile.rails-4.1.rb
    - rvm: 2.4.7
      gemfile: gemfiles/Gemfile.rails-6.0.rb
    - rvm: 2.5.6
      gemfile: gemfiles/Gemfile.rails-4.0.rb
    - rvm: 2.5.6
      gemfile: gemfiles/Gemfile.rails-4.1.rb
    - rvm: 2.5.6
      gemfile: gemfiles/Gemfile.rails-5.0.rb
    - rvm: 2.5.6
      gemfile: gemfiles/Gemfile.rails-5.1.rb
    - rvm: 2.6.4
      gemfile: gemfiles/Gemfile.rails-4.0.rb
    - rvm: 2.6.4
      gemfile: gemfiles/Gemfile.rails-4.1.rb
    - rvm: 2.6.4
      gemfile: gemfiles/Gemfile.rails-5.0.rb
    - rvm: 2.6.4
      gemfile: gemfiles/Gemfile.rails-5.1.rb

before_script:
  - bundle exec rake db:create db:up

script: 'bundle exec rake test'
