rvm:
  - 1.9.3
  - 1.8.7

branches:
  only:
    - master
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite3

gemfile:
  - gemfiles/Gemfile.rails-3.0.rb
  - gemfiles/Gemfile.rails-3.1.rb
  - gemfiles/Gemfile.rails-3.2.rb
before_script: 'bundle exec rake db:reset db:up'
script: 'bundle exec rake test'
