language: ruby
cache: bundler

rvm:
  - 2.4.0
  - 2.3.0
  - 2.2.0
  - 2.1.0
  - jruby-9.1.13.0

env:
  - DB=postgres
  - DB=mysql

gemfile:
  - gemfiles/Gemfile.rails-4.0.rb
  - gemfiles/Gemfile.rails-4.1.rb
  - gemfiles/Gemfile.rails-4.2.rb
  - gemfiles/Gemfile.rails-5.0.rb
  - gemfiles/Gemfile.rails-5.1.rb

before_install:
  - gem update bundler

matrix:
  exclude:
    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-5.0.rb
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-5.0.rb
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5.1.rb
    - rvm: 2.1.0
      gemfile: gemfiles/Gemfile.rails-5.1.rb
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-5.1.rb
    - rvm: 2.4.0
      gemfile: gemfiles/Gemfile.rails-4.0.rb
    - rvm: 2.4.0
      gemfile: gemfiles/Gemfile.rails-4.1.rb

sudo: false

before_script:
  - bundle exec rake db:create db:up

script: 'COVERALLS=true bundle exec rake test'
