language: ruby
rvm:
  - 2.0.0
  - jruby-19mode
  - rbx
env:
  - DB=postgres
  - DB=mysql
gemfile:
  - gemfiles/Gemfile.rails-4.0.rb
  - gemfiles/Gemfile.rails-stable.rb
  - gemfiles/Gemfile.rails-4.1.rb

before_script: 'bundle exec rake db:create db:up'
script: 'COVERAGE=true bundle exec rake test'
matrix:
  allow_failures:
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails-4.1.rb
      env: DB=postgres
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails-4.1.rb
      env: DB=mysql
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails-4.1.rb
      env: DB=sqlite3
