rvm:
  - 1.9.3
  - ree
  - rbx
  - rbx-2.0
  - 1.9.2
  - 1.8.7
  - jruby

branches:
  only:
    - 4.0.0
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite3

gemfile:
  - gemfiles/Gemfile.rails-3.0.rb
  - gemfiles/Gemfile.rails-3.1.rb

script: "bundle exec rake db:reset db:up test"
