rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - rbx-2.0
  # Temporarily not testing JRuby in CI because ActiveRecord JDBC does not
  # support 3.1 well yet. Rest assured I'm testing this and want to target
  # JRuby, I just don't want to see broken build messages all the time when I
  # already know what the probelem is.
  # - jruby

branches:
  only:
    - 4.0.0
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite3

gemfile:
  - gemfiles/Gemfile.rails-3.0.rb
  - gemfiles/Gemfile.rails-3.1.rb

script: "bundle exec rake db:reset db:up test"
